version: "3"

services:
  db:
    image: supabase/postgres:14.1.0.105
    container_name: supavisor-db
    ports:
      - "6432:5432"
    volumes:
      - ./dev/postgres:/docker-entrypoint-initdb.d/
      # Uncomment to set MD5 authentication method on unitialized databases
      # - ./dev/postgres/md5/etc/postgresql/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_HOST: /var/run/postgresql
      POSTGRES_PASSWORD: postgres
      # Uncomment to set MD5 authentication method on unitialized databases
      # POSTGRES_INITDB_ARGS: --auth-host=md5
    db12:
      image: supabase/postgres:12.5.0
      container_name: supavisor-db-12
      ports:
        - "6433:5432"
      volumes:
        - ./dev/postgres12:/docker-entrypoint-initdb.d/
      command:
      - postgres
      - -c
      - wal_level=logical
      environment:
        POSTGRES_PASSWORD: postgres
