name: Build and Release binary on Push to Master
on:
  release:
    types: [published]
    branches:
      - main
jobs:
  generate_binary:
    name: Create binary release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: 25.x # Define the OTP version [required]
          elixir-version: 1.14.x # Define the elixir version [required]
          experimental-otp: true # see https://github.com/actions/setup-elixir/issues/49
      - name: Cache Mix
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Setup Zig for burrito
        uses: goto-bus-stop/setup-zig@v2
      - name: Create release
        run: mix release supavisor_bin
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: "supavisor_bin-${GITHUB_REF#refs/*/}"
          release-tag: v${GITHUB_REF#refs/*/}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
